# Problem 1
Write a program that plays Tic-Tac-Toe with a user. Use ndarrays

Each round, the game prints out the state of the board, asks the user where they would like to place their mark, and implements this decision. 

The program then places its own mark on a randomly chosen available position. Once one of the plaers won, the program declares the result and asks if the user would like to continue. The first player is seleccted at random. 

Think about what kind of program structure would make it easy to develop extensions such as a more sophisticated AI, an ability to play with another program, or play the game on boards of arbitrary rectangular shape. Also, think about objects and classes that wold make sense to deevelop and the three pillars of OOP. 

In [ ]:
import numpy as np
import random 
numpy.__version__
np.set_printoptions(precision=3)

In [26]:
import numpy as np
import random
import matplotlib.pyplot as plt

#class tictactoe:
    #def __init__(self): #constructor
     #   self.A = np.zeros((3,3), dtype=int) #array of 0s #this creates the board
      #  self.player = 1
def create_board():
    tictactoeboard = np.zeros((3,3))
    return tictactoeboard # Create a 3x3 array of zeros that will be updated
def place(tictactoeboard, player, pos):  #Have to update the position of the player on the board
    if tictactoeboard[pos] == 0:
        tictactoeboard[pos] = player
        return tictactoeboard # Update board with the players pick
    else:
        print('Please pick another spot, spot taken.') # Make sure open spot is taken
        return tictactoeboard
def allpossibilities(tictactoeboard): #What are all the positions available to pick from?
        #Want to see where the 0's on the board are
    return list(zip(*np.where(tictactoeboard == 0)))
def random_places(tictactoeboard, player): #Where can the player place a marker on the board
        #What are the possibilities? 
    selections = allpossibilities(tictactoeboard)
        # Get the length of the all the selections
    if len(selections) > 0:
        selections = random.choice(selections) # randomly selects one item 
        place(tictactoeboard, player, selections)
    return tictactoeboard
    random_places(tictactoeboard, 2)
#Who has won the game? Check all rows
def row_win(tictactoeboard, player):
    if np.any((np.all(tictactoeboard == player, axis=1))): #We are checking whether any row contains all positions that are the same for the player
        return True
    else:
        return False
    row_win(tictactoeboard, 1)

#Who has won the game, check all columns
def col_win(tictactoeboard, player):
    if np.any((np.all(tictactoeboard == player, axis=0))): #We are checking whether any col contains all positions that are the same for the player
        return True
    else:
        return False
    col_win(tictactoeboard, 1)

def diag_win(tictactoeboard, player):
    if np.all(np.diag(tictactoeboard)==player) or np.all(np.diag(np.fliplr(tictactoeboard))==player):
        #np.diag returns diagonal of array
        #np.fliplr rearranges the columns in a reverse order to get other diagonal
        return True
    else: 
        return False
    diag_win(tictactoeboard, 1)
    

def result(tictactoeboard, player):
    winner = 0 #initialize
    for player in [1,2]:
        if row_win(tictactoeboard, player) or col_win(tictactoeboard, player) or diag_win(tictactoeboard, player):
            winner = player
        if np.all(tictactoeboard != 0) and winner == 0:
            winner = -1
        return winner
result(tictactoeboard, 1)


def fullgame():
    tictactoeboard = create_board()
    winner = 0
    while winner == 0:
        for player in [1,2]:
            random_places(tictactoeboard, player)
            winner = result(tictactoeboard, 1)
            if winner !=0:
                break
    return winner




def play():
    tictactoeboard = create_board()
    print("Here is the board.")
    print(tictactoeboard) #view board
    print() #new line
    print("Type your row number and the column number for spot.")
    print("E.g: Middle position would mean 2,2 (without spaces).")
    order = int(input("First or second? (1/2) "))

    if order == 1:
        player1 = 1
        player2 = 2
        players = [player1, player2]
    else:
        player1 = 2
        player2 = 1
        players = [player2, player1]
    print("You are player {}:".format(order))
    winner = 0
    while winner == 0:
        for player in players:
            if player == order:
                pos = input("What position do you want to place? ")
                print("You want to place at {} position.".format(pos))
                pos = int(pos[0])-1, int(pos[2])-1
                place(tictactoeboard, player1, pos) # will break if position is not 0 (empty)
                print(tictactoeboard)
            else:
                print("My move:")
                random_places(tictactoeboard, player)
                print(tictactoeboard)
            winner = result(tictactoeboard, players)
            if winner > 0:
                if winner == order:
                    print("You win.")
                else:
                    print("I win.")
                break
            elif winner == -1:
                print("Tie game.")
                break
            print()
    return winner

def main(): #Combine functions to play game.
    print('GAME OF TIC TAC TOE')
    play()

main()

GAME OF TIC TAC TOE
Here is the board.
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Type your row number and the column number for spot.
E.g: Middle position would mean 2,2 (without spaces).
First or second? (1/2) 1
You are player 1:
What position do you want to place? 1,1
You want to place at 1,1 position.
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

My move:
[[1. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

What position do you want to place? 2.1
You want to place at 2.1 position.
[[1. 2. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]

My move:
[[1. 2. 0.]
 [1. 0. 0.]
 [0. 2. 0.]]

What position do you want to place? 3,1
You want to place at 3,1 position.
[[1. 2. 0.]
 [1. 0. 0.]
 [1. 2. 0.]]
You win.
